

-- ----------------------------
-- Event structure for `auto_create_record_table`
-- ----------------------------
DROP PROCEDURE IF EXISTS `AUTO_CREATE_UE_INFO_PROCEDURE`;
DROP EVENT IF EXISTS `AUTO_CREATE_UE_INFO_EVENT`;

DELIMITER $$

CREATE PROCEDURE AUTO_CREATE_UE_INFO_PROCEDURE()
BEGIN
DECLARE ueInfoTabName VARCHAR(30);

SET @ueInfoDay = DATE_FORMAT(DATE_ADD(CURDATE(), INTERVAL 1 DAY),'%Y-%m-%d');
SET @ueInfoTabName = CONCAT('t_ue_info_', DATE_FORMAT(DATE_ADD(CURDATE(), INTERVAL 1 DAY),'%Y_%m_%d'));

SET @STMT :=CONCAT("CREATE TABLE ", @ueInfoTabName , "(
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'Ue信息ID',
    `SITE_NAME` varchar(40) DEFAULT NULL COMMENT '站点名称',
    `DEVICE_SN` varchar(40) DEFAULT NULL COMMENT '子设备序列号',
    `SITE_SN` varchar(40) DEFAULT NULL,
    `IMSI` varchar(16) DEFAULT NULL COMMENT 'IMSI',
    `IMEI` varchar(16) DEFAULT NULL COMMENT 'IMEI',
    `STMSI` varchar(20) DEFAULT NULL COMMENT 'TMSI',
    `MAC` varchar(20) DEFAULT NULL COMMENT 'MAC地址',
    `LATYPE` varchar(4) DEFAULT NULL COMMENT '位置更新类型',
    `INDICATION` tinyint(2) DEFAULT '0' COMMENT '是否目标手机：0 --- NORMAL；1--- 黑名单手机；2--- 特殊归属地手机',
    `REALTIME` tinyint(1) DEFAULT '0' COMMENT '是否实时上报:00-  不实时上报;01-  实时上报',
    `CAPTURE_TIME` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '基站侧记录的上号时间',
    `RARTA` bigint(20) DEFAULT NULL,
    `CREATE_TIME` varchar(14) DEFAULT NULL COMMENT '创建时间',
    `CITY_NAME` varchar(100) DEFAULT NULL COMMENT '归属地地名',
    `CITY_CODE` varchar(10) DEFAULT NULL,
    `BAND` varchar(20) DEFAULT NULL COMMENT '运营商',
    `OPERATOR` varchar(20) DEFAULT NULL COMMENT '运营商',
    PRIMARY KEY (`ID`),
    KEY `DEVICE_SN` (`SITE_NAME`),
    KEY `SUBDEVICE_SN` (`DEVICE_SN`),
    KEY `IMSI` (`IMSI`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='终端信息采集表' ");

SET @INSER_SHARDING_INFO_STMT = "INSERT INTO t_sharding_tab_info ( SHARDING_TAB_NAME, SHARDING_TAB_DATE ) VALUES( ?, ?)";

PREPARE STMT FROM @STMT;
EXECUTE STMT;

PREPARE INSER_SHARDING_INFO_STMT FROM @INSER_SHARDING_INFO_STMT;
EXECUTE INSER_SHARDING_INFO_STMT USING @ueInfoTabName, @ueInfoDay ;

END;
$$

CREATE DEFINER=`root`@`%` EVENT `AUTO_CREATE_UE_INFO_EVENT`
ON SCHEDULE EVERY 1 DAY STARTS '2016-12-31 23:00:00'
ON COMPLETION PRESERVE
ENABLE
DO
BEGIN
CALL AUTO_CREATE_UE_INFO_PROCEDURE();
END
$$

DELIMITER ;

